/*
Warm up

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
<<<<<<< HEAD

var a = 1
var b = 1
var c = ' '
var total = 0
for( c = a + b; c < 4000000; c + b ) {
  c = a + b;
  b = c;
  a = c-a;
  if(c % 2 === 0){
  total += c;
} if (c >= 4000000) {
  break;
}
}
console.log(total);
=======
>>>>>>> 9d8c264deeba832960354784ef7ac77700c62292
